### PR TITLE
utils_conn: Fix no attribute 'RemoteFile' issue

### PR DESCRIPTION
**Pull request by Yingshun**
It reports an error - module 'aexpect.remote' has no attribute
'RemoteFile' when creating TLSConnection or TCPConnection.

Signed-off-by: Yingshun Cui <yicui@redhat.com>

### CODE REVIEW

**Comment by Yingshun** [comment]
**Test result:**
_Before fix:_
```
# avocado run --vt-type libvirt --vt-machine-type q35 virsh.migrate_vm.positive_testing.p2p_migration.basic.with_tls.with_postcopy --vt-connect-uri qemu:///system
JOB ID     : a35dbb6461028ea99abfbb1620779ce3ae1a7568
JOB LOG    : /root/avocado/job-results/job-2020-10-20T01.31-a35dbb6/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.p2p_migration.basic.with_tls.with_postcopy: ERROR: module 'aexpect.remote' has no attribute 'RemoteFile' (61.25 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 64.72 s
```

_After fix:_
```
avocado run --vt-type libvirt --vt-machine-type q35 virsh.migrate_vm.positive_testing.p2p_migration.basic.with_tls.with_postcopy --vt-connect-uri qemu:///system
JOB ID     : e17fab78349574797b7339c95653fee2a47e7363
JOB LOG    : /root/avocado/job-results/job-2020-10-20T01.37-e17fab7/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.p2p_migration.basic.with_tls.with_postcopy: PASS (249.82 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 253.29 s

```

**Comment by Yingshun** [comment]
It's introduced by 2e361394efde1468f.

**Review by chloerh — APPROVED** [review]

**Review by pevogam — APPROVED** [review]
LGTM

**Review by dzhengfy — APPROVED** [review]
LGTM
