### PR TITLE
Hotfix for the RuntimeError during Postprocess

### PR DESCRIPTION
**Pull request by luckyh**
The following failure could be emitted during `Postprocess`:

  RuntimeError: Failures occurred while postprocess:

  Postprocess: 'NoneType' object has no attribute 'cleanup_daemons'

it is introduced by commit 0148461, and because a qemu VM instance are
being `postprocess` without called `create` at its lifetime.

Signed-off-by: Xu Han <xuhan@redhat.com>

### CODE REVIEW

**Comment by luckyh** [comment]
@pevogam @sathnaga @YongxueHong would you please help review this one? thanks!

**Comment by sathnaga** [comment]
No issues seen.
```
# avocado run boot --vt-type qemu --vt-guest-os Fedora.31.ppc64le --vt-qemu-bin /usr/share/avocado-plugins-vt/bin/qemu --vt-extra-params backup_image_before_test=no restore_image_after_test=no qemu_binary=/usr/share/avocado-plugins-vt/bin/qemu
/usr/local/lib/python3.7/site-packages/avocado_framework-79.0-py3.7.egg/avocado/plugins/run.py:286: FutureWarning: The following arguments will be changed to boolean soon: sysinfo, output-check, failfast and keep-tmp. 
  FutureWarning)
JOB ID     : dc6b626be18e39b17e5449ece25abd745f8abf15
JOB LOG    : /home/kvmci/tests/results/job-2020-05-12T01.17-dc6b626/job.log
 (1/1) io-github-autotest-qemu.boot: PASS (444.17 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 446.28 s
JOB HTML   : /home/kvmci/tests/results/job-2020-05-12T01.17-dc6b626/results.html
```

**Comment by luckyh** [comment]
Thanks!
